name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: microsoft/setup-msbuild@v3
      with:
        vs-version: '17'

    - name: Build
      run: msbuild igdl.vcxproj /p:Configuration=Release /p:PlatformToolset=v143

    - name: Release
      run: |
        gh release upload release --clobber Release/libEGL.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

